name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Download op-reth
        run: |
          ./scripts/download-op-reth.sh
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Log Op-reth version
        run: |
          op-reth --version

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test --features integration -- integration::integration_test::tests
